// AUTO-GENERATED by scripts/fetch-exercise-images.mjs — do not edit by hand.
// Demonstration images from free-exercise-db (https://github.com/yuhonas/free-exercise-db, MIT).
// Maps our exercise id -> local image paths (precached by the PWA for offline use).

export const EXERCISE_IMAGES: Record<string, string[]> = {
  "db-bench-press": [
    "/exercises/db-bench-press/0.jpg",
    "/exercises/db-bench-press/1.jpg"
  ],
  "barbell-bench-press": [
    "/exercises/barbell-bench-press/0.jpg",
    "/exercises/barbell-bench-press/1.jpg"
  ],
  "incline-db-press": [
    "/exercises/incline-db-press/0.jpg",
    "/exercises/incline-db-press/1.jpg"
  ],
  "push-up-variations": [
    "/exercises/push-up-variations/0.jpg",
    "/exercises/push-up-variations/1.jpg"
  ],
  "push-up": [
    "/exercises/push-up/0.jpg",
    "/exercises/push-up/1.jpg"
  ],
  "dips": [
    "/exercises/dips/0.jpg",
    "/exercises/dips/1.jpg"
  ],
  "db-fly": [
    "/exercises/db-fly/0.jpg",
    "/exercises/db-fly/1.jpg"
  ],
  "cable-crossover": [
    "/exercises/cable-crossover/0.jpg",
    "/exercises/cable-crossover/1.jpg"
  ],
  "overhead-press": [
    "/exercises/overhead-press/0.jpg",
    "/exercises/overhead-press/1.jpg"
  ],
  "barbell-ohp": [
    "/exercises/barbell-ohp/0.jpg",
    "/exercises/barbell-ohp/1.jpg"
  ],
  "arnold-press": [
    "/exercises/arnold-press/0.jpg",
    "/exercises/arnold-press/1.jpg"
  ],
  "lateral-raise": [
    "/exercises/lateral-raise/0.jpg",
    "/exercises/lateral-raise/1.jpg"
  ],
  "band-lateral-raise": [
    "/exercises/band-lateral-raise/0.jpg",
    "/exercises/band-lateral-raise/1.jpg"
  ],
  "triceps-pushdown": [
    "/exercises/triceps-pushdown/0.jpg",
    "/exercises/triceps-pushdown/1.jpg"
  ],
  "overhead-triceps-ext": [
    "/exercises/overhead-triceps-ext/0.jpg",
    "/exercises/overhead-triceps-ext/1.jpg"
  ],
  "db-skullcrusher": [
    "/exercises/db-skullcrusher/0.jpg",
    "/exercises/db-skullcrusher/1.jpg"
  ],
  "close-grip-push-up": [
    "/exercises/close-grip-push-up/0.jpg",
    "/exercises/close-grip-push-up/1.jpg"
  ],
  "band-triceps-pushdown": [
    "/exercises/band-triceps-pushdown/0.jpg",
    "/exercises/band-triceps-pushdown/1.jpg"
  ],
  "pull-ups": [
    "/exercises/pull-ups/0.jpg",
    "/exercises/pull-ups/1.jpg"
  ],
  "chin-up": [
    "/exercises/chin-up/0.jpg",
    "/exercises/chin-up/1.jpg"
  ],
  "single-arm-row": [
    "/exercises/single-arm-row/0.jpg",
    "/exercises/single-arm-row/1.jpg"
  ],
  "bent-over-row": [
    "/exercises/bent-over-row/0.jpg",
    "/exercises/bent-over-row/1.jpg"
  ],
  "db-row": [
    "/exercises/db-row/0.jpg",
    "/exercises/db-row/1.jpg"
  ],
  "lat-pulldown": [
    "/exercises/lat-pulldown/0.jpg",
    "/exercises/lat-pulldown/1.jpg"
  ],
  "band-row": [
    "/exercises/band-row/0.jpg",
    "/exercises/band-row/1.jpg"
  ],
  "face-pulls": [
    "/exercises/face-pulls/0.jpg",
    "/exercises/face-pulls/1.jpg"
  ],
  "band-pull-apart": [
    "/exercises/band-pull-apart/0.jpg",
    "/exercises/band-pull-apart/1.jpg"
  ],
  "rear-delt-fly": [
    "/exercises/rear-delt-fly/0.jpg",
    "/exercises/rear-delt-fly/1.jpg"
  ],
  "shrug": [
    "/exercises/shrug/0.jpg",
    "/exercises/shrug/1.jpg"
  ],
  "db-curl": [
    "/exercises/db-curl/0.jpg",
    "/exercises/db-curl/1.jpg"
  ],
  "hammer-curl": [
    "/exercises/hammer-curl/0.jpg",
    "/exercises/hammer-curl/1.jpg"
  ],
  "barbell-curl": [
    "/exercises/barbell-curl/0.jpg",
    "/exercises/barbell-curl/1.jpg"
  ],
  "band-curl": [
    "/exercises/band-curl/0.jpg",
    "/exercises/band-curl/1.jpg"
  ],
  "concentration-curl": [
    "/exercises/concentration-curl/0.jpg",
    "/exercises/concentration-curl/1.jpg"
  ],
  "wrist-curl": [
    "/exercises/wrist-curl/0.jpg",
    "/exercises/wrist-curl/1.jpg"
  ],
  "goblet-squat": [
    "/exercises/goblet-squat/0.jpg",
    "/exercises/goblet-squat/1.jpg"
  ],
  "back-squat": [
    "/exercises/back-squat/0.jpg",
    "/exercises/back-squat/1.jpg"
  ],
  "front-squat": [
    "/exercises/front-squat/0.jpg",
    "/exercises/front-squat/1.jpg"
  ],
  "bulgarian-split-squat": [
    "/exercises/bulgarian-split-squat/0.jpg",
    "/exercises/bulgarian-split-squat/1.jpg"
  ],
  "romanian-deadlift": [
    "/exercises/romanian-deadlift/0.jpg",
    "/exercises/romanian-deadlift/1.jpg"
  ],
  "deadlift": [
    "/exercises/deadlift/0.jpg",
    "/exercises/deadlift/1.jpg"
  ],
  "walking-lunge": [
    "/exercises/walking-lunge/0.jpg",
    "/exercises/walking-lunge/1.jpg"
  ],
  "step-up": [
    "/exercises/step-up/0.jpg",
    "/exercises/step-up/1.jpg"
  ],
  "leg-press": [
    "/exercises/leg-press/0.jpg",
    "/exercises/leg-press/1.jpg"
  ],
  "leg-extension": [
    "/exercises/leg-extension/0.jpg",
    "/exercises/leg-extension/1.jpg"
  ],
  "leg-curl": [
    "/exercises/leg-curl/0.jpg",
    "/exercises/leg-curl/1.jpg"
  ],
  "nordic-curl": [
    "/exercises/nordic-curl/0.jpg",
    "/exercises/nordic-curl/1.jpg"
  ],
  "hip-thrust": [
    "/exercises/hip-thrust/0.jpg",
    "/exercises/hip-thrust/1.jpg"
  ],
  "glute-bridge": [
    "/exercises/glute-bridge/0.jpg",
    "/exercises/glute-bridge/1.jpg"
  ],
  "kb-swing": [
    "/exercises/kb-swing/0.jpg",
    "/exercises/kb-swing/1.jpg"
  ],
  "calf-raise": [
    "/exercises/calf-raise/0.jpg",
    "/exercises/calf-raise/1.jpg"
  ],
  "seated-calf-raise": [
    "/exercises/seated-calf-raise/0.jpg",
    "/exercises/seated-calf-raise/1.jpg"
  ],
  "farmer-carry": [
    "/exercises/farmer-carry/0.jpg",
    "/exercises/farmer-carry/1.jpg"
  ],
  "plank-hold": [
    "/exercises/plank-hold/0.jpg",
    "/exercises/plank-hold/1.jpg"
  ],
  "plank": [
    "/exercises/plank/0.jpg",
    "/exercises/plank/1.jpg"
  ],
  "hanging-leg-raise": [
    "/exercises/hanging-leg-raise/0.jpg",
    "/exercises/hanging-leg-raise/1.jpg"
  ],
  "cable-crunch": [
    "/exercises/cable-crunch/0.jpg",
    "/exercises/cable-crunch/1.jpg"
  ],
  "crunch": [
    "/exercises/crunch/0.jpg",
    "/exercises/crunch/1.jpg"
  ],
  "bicycle-crunch": [
    "/exercises/bicycle-crunch/0.jpg",
    "/exercises/bicycle-crunch/1.jpg"
  ],
  "russian-twist": [
    "/exercises/russian-twist/0.jpg",
    "/exercises/russian-twist/1.jpg"
  ],
  "side-plank": [
    "/exercises/side-plank/0.jpg",
    "/exercises/side-plank/1.jpg"
  ],
  "dead-bug": [
    "/exercises/dead-bug/0.jpg",
    "/exercises/dead-bug/1.jpg"
  ],
  "ab-wheel": [
    "/exercises/ab-wheel/0.jpg",
    "/exercises/ab-wheel/1.jpg"
  ],
  "cat-cow-stretch": [
    "/exercises/cat-cow-stretch/0.jpg",
    "/exercises/cat-cow-stretch/1.jpg"
  ],
  "world-s-greatest-stretch": [
    "/exercises/world-s-greatest-stretch/0.jpg",
    "/exercises/world-s-greatest-stretch/1.jpg"
  ],
  "child-s-pose": [
    "/exercises/child-s-pose/0.jpg",
    "/exercises/child-s-pose/1.jpg"
  ],
  "mountain-climbers": [
    "/exercises/mountain-climbers/0.jpg",
    "/exercises/mountain-climbers/1.jpg"
  ]
};

/** Image paths for an exercise id, or [] when none (UI falls back to the movement icon). */
export function exerciseImages(id: string): string[] {
  return EXERCISE_IMAGES[id] ?? [];
}
